# Generated by Django 2.2.9 on 2020-04-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_news_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coins',
            old_name='name',
            new_name='coin_name',
        ),
    ]
